### ISSUE TITLE
Faulty check in PluginAPI.js

### ISSUE THREAD

**Issue by kbrabrand** [aptoma/drpublish-plugin-api#14]
When running with the most up-to-date version of the master branch there is a faulty check in the `request` method of PluginAPI.js. It was fixed with e0b10a272c5422659798c9ad81863b52573893d9, but this commit has not yet been merged into `master`.

This fix has not been merged into master, so there is currently no easy way to get that bug fixed. Able to merge changes from develop->master?

**Comment by kbrabrand** [comment]
@mipli @arasix ?

**Comment by mipli** [comment]
Will fix this now

**Comment by mipli** [comment]
Have now tagged release v2.1 with this fix included

**Comment by kbrabrand** [comment]
Great. Thanks
